server:
  port: 8080

spring:
  application:
    name: workflow-admin
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  
  security:
    user:
      name: admin
      password: admin
  
  # Flowable配置
  flowable:
    database-schema-update: true
    async-executor-activate: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.workflow.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: admin
  expiration: 86400000  # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.example.workflow: DEBUG
    org.flowable: INFO